services:
  postgres-db:
    container_name: bookstore-db_postgres
    image: postgres:12-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bookstore-network

  mongo-db:
    container_name: bookstore-db_mongo
    image: mongo:5.0
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

    ports:
      - ${MONGO_PORT}:27017
    networks:
      - bookstore-network
    volumes:
      - ./database/shop.js:/docker-entrypoint-initdb.d/shop.js:ro

  tienda-api-rest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore-api-rest
    restart: always
    env_file: .env
    ports:
      - ${API_PORT}:3000
    volumes:
      - book-images:/app/book-images
    networks:
      - bookstore-network

volumes:
  book-images:

networks:
  bookstore-network:
    driver: bridge